---
abstract: 'Break tasks into labeld units of work that are trackable across hosts and helper systems.'
author:
  - 'Mark Swayne <daotoad@cpan.org>'
build_requires:
  Data::Dumper: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Work
requires:
  Carp: 0
  Exporter: 0
  Log::Lager: 0
  Log::Lager::Message: 0
  Scalar::Util: 0
  Socket: 0
  Sys::Hostname: 0
  Time::HiRes: 0
  strict: 0
  warnings: 0
version: 0.04.01
