#!/bin/env/perl

use strict;
use warnings;

use Data::Dumper;
use lib 'lib';

use Log::Work;
use Log::Event;
use Log::Lager 'I';

use Log::Lager::Work;
use Log::Lager::Event;
use Log::ProvenanceId 'Wubba.wubba';

Log::Lager::Event->register_standard_handlers;
Log::Lager::Work->register_standard_handlers;

my $foo = {
    bar => 123,
    baz => 54,
};

INFO WORK {
    INFO EVENT "I like cheese.";
    INFO EVENT $foo;
    bless $foo, 'Pterodactyl';
    INFO EVENT $foo;
    INFO EVENT "I still like cheese", $foo;
    INFO EVENT {
        name => 'Frank',
        species => 'herring',
    };
} 'Monkey monkey', 'ProvID.Here';


=pod

INFO EVENT 'Name goes here', even => key, value => 'pairs';

INFO EVENT  { even => key, value => 'pairs' }, 'Name goes here';

INFO EVENT  { even => key, value => 'pairs' } 'Name goes here';

INFO EVENT 'Name goes here' => ( key => 'value', pairs => '!' );

INFO WORK { balrg } 'Name here';





